#!/bin/bash
curl https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py -O
chmod +x ./awslogs-agent-setup.py
./awslogs-agent-setup.py -n -r us-east-1 -c s3://bankingtest123/awslogger.cnf
logger Hey this is a test Centos
sudo yum install git
git clone https://github.com/tsmith1119s/centosInspec.git
cd centosInspec
runuser -l  centos -c 'bash AutomateScript'
#Launch script that should be placed in user data