#!/bin/bash
#install the aws cloudwatch client
curl https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py -O
chmod +x ./awslogs-agent-setup.py
./awslogs-agent-setup.py -n -r us-east-1 -c s3://bankingtest123/awslogger.cnf
logger Hey this is a test Centos
#install the inspec software
curl -o inspec.rpm https://packages.chef.io/files/stable/inspec/1.7.1/el/7/inspec-1.7.1-1.el7.x86_64.rpm
rpm -Uvh inspec.rpm 
#install git
sudo yum install git -y
git clone https://github.com/tsmith60/inspecrepo.git
cd inspecrepo
runuser -l  centos -c 'bash /inspecrepo/AutomateScript.sh'
#Launch script that should be placed in user data